### PR TITLE
Fixed security issue for new users (without org) - Frontend

### PR DESCRIPTION
**Pull request by vasolga**
When somebody is signed in with their email and they aren't part of an organization they will not have access to the page.

### CODE REVIEW

**Review by zoexili — COMMENTED** [review]
There is one test failed, can you please check?

**Comment by vasolga** [comment]
I saw the issue in the PR. The test runs without errors locally; the issue is when running the test in github actions.

During the action test github does not have access to the REACT_APP_CLERK_PUBLISHABLE_KEY and this is causing it to fail the test, since it cannot access the app to check for the test. In some way we have to add that key to the action workflow so it can run the test. I know we cannot add the key to the open github repo, but we could add it as a secret variable to access during actions (see here https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions).

This change is made in the settings of the repo, which I don’t have permissions to access. I believe the way to solve it is (and also for future tests):
* Add the keys to access the app as secrets in github
* Change the actions workflow to access them during test running

**Comment by malbaker** [comment]
I agree with Olga, we can just add the Clerk key as a repo secret so it can be safely referenced in the testing workflow

**Review by malbaker — APPROVED** [review]

**Comment by zoexili** [comment]
Yes that's the reason. I added the key as a repo secret and it's not working. Editing the yml file may help.

**Pull request merged**
